spring:
  application:
    name: login-intelipost-microservice
  session:
    store-type: redis
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    initiliaze: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  redis:
    host: localhost

server:
  port: 8081


eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka

jwt:
  secret: essaVagaEMinha
  expiration: 60000
---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
  redis:
    host: redis
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    hostname: localhost